%gconf.xml etc/skel/.gconf/desktop/gnome/applications/window_manager/
fgss.desktop usr/share/applications/
net-check.desktop usr/share/applications/
bin/net_check usr/bin/
launch-install-fg-restricted-extras.desktop usr/share/applications/
gnome-power-manager/%gconf.xml etc/skel/.gconf/apps/gnome-power-manager/notify/
bin/launch-install-fg-restricted-extras usr/bin/
bin/install-fg-restricted-extras usr/sbin/
